{
  "hash": "5f49796b943cb8ead68c063c0fa9dac3",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Covariates and the time grid\"\n---\n\n\n\n\nThe emulator takes twelve numbers, describing the setting as it stands and the campaign being\nevaluated.\n\n## The twelve covariates\n\nThe checkpoint carries the names and their canonical order.\n\n::: {#e72d456a .cell execution_count=1}\n``` {.python .cell-code}\nfrom stateMINT.model import Mamba2Regressor\n\nartifact = Mamba2Regressor.from_pretrained(\n    \"dide-ic/stateMINT\", predictor=\"prevalence\",\n)\n\nfor i, name in enumerate(artifact.preprocessing_config[\"static_covars\"], start=1):\n    print(f\"{i:2d}. {name}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n 1. eir\n 2. dn0_use\n 3. dn0_future\n 4. Q0\n 5. phi_bednets\n 6. seasonal\n 7. routine\n 8. itn_use\n 9. irs_use\n10. itn_future\n11. irs_future\n12. lsm\n```\n:::\n:::\n\n\nPass them as a dictionary, one per scenario, and the order above takes care of itself.\n\n| Covariate | Meaning | Range | Where it comes from |\n|---|---|---|---|\n| `eir` | Infectious bites per person per year | > 0, roughly 0.1–200 | [estiMINT](../04-estimint/estimating-eir.qmd), from a measured prevalence |\n| `dn0_use` | Probability a mosquito dies on contact with a treated net, under the nets in place now | 0–0.56 | `calculate_dn0` on the current net mix ([Nets and dn0](../04-estimint/nets-and-dn0.qmd)) |\n| `dn0_future` | The same probability, under the campaign net | 0–0.56 | `calculate_dn0` on the campaign net mix |\n| `Q0` | Human blood index | 0–1, typically 0.7–0.95 | Vector species bionomics |\n| `phi_bednets` | Share of bites taken while people are in bed | 0–1, typically 0.6–0.9 | Vector species bionomics |\n| `seasonal` | Transmission profile. 0 perennial, 1 strongly seasonal | 0 or 1 | The setting |\n| `routine` | Routine (continuous) net distribution running alongside the campaign | 0 or 1 | The campaign |\n| `itn_use` | ITN coverage now | 0–1 | Survey or programme data |\n| `irs_use` | IRS coverage now | 0–1 | Programme data |\n| `itn_future` | ITN coverage from the campaign onwards | 0–1 | The campaign |\n| `irs_future` | IRS coverage from the campaign onwards | 0–1 | The campaign |\n| `lsm` | Larval source management coverage from the campaign onwards | 0–1 | The campaign |\n\nThe emulator reads `dn0_use` and `itn_use` as a pair rather than as independent knobs. The two\ndescribe the nets between them. Omitting any of the twelve raises a `ValueError` that names the\nkeys left out.\n\n::: {#7ad324cf .cell execution_count=2}\n``` {.python .cell-code}\ncovars = {\n    \"eir\": 31.96, \"dn0_use\": 0.311, \"dn0_future\": 0.485,\n    \"Q0\": 0.85, \"phi_bednets\": 0.80, \"seasonal\": 0,\n    \"routine\": 0.0, \"itn_use\": 0.70, \"irs_use\": 0.0,\n    \"itn_future\": 0.70, \"irs_future\": 0.0, \"lsm\": 0.0,\n}\n\nincomplete = {k: v for k, v in covars.items() if k != \"lsm\"}\n\ntry:\n    artifact.predict([incomplete])\nexcept ValueError as err:\n    print(f\"{type(err).__name__}: {err}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nValueError: Missing static covariates: ['lsm']\n```\n:::\n:::\n\n\n## `_use` and `_future`\n\nThree quantities appear twice, with the `_use` suffix for the world before the campaign and the\n`_future` suffix for the campaign itself, in force from day 3285 onwards. `lsm` and `routine`\nhave no `_use` counterpart.\n\n## The pre-campaign window\n\nFive covariates (`dn0_future`, `itn_future`, `irs_future`, `lsm` and `routine`) are held at\nzero for every timestep before the intervention day, whatever value is passed, and take that\nvalue only from day 3285 onwards.\n\n::: {#55aee265 .cell execution_count=3}\n``` {.python .cell-code}\nprint(artifact.preprocessing_config[\"after_intervention\"])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n['dn0_future', 'itn_future', 'irs_future', 'lsm', 'routine']\n```\n:::\n:::\n\n\nTwo scenarios that differ only in their campaign fields therefore have identical feature\nmatrices until the campaign starts.\n\n::: {#a32a2842 .cell execution_count=4}\n``` {.python .cell-code}\nimport numpy as np\n\nwithdraw = dict(covars, dn0_future=0.0, itn_future=0.0, irs_future=0.0, lsm=0.0, routine=0.0)\npackage  = dict(covars, dn0_future=0.55, itn_future=0.90, irs_future=0.60, lsm=0.30, routine=1.0)\n\nX = artifact.prepare_inputs([withdraw, package])\nidentical = np.isclose(X[0], X[1]).all(axis=1)\nfirst_difference = int(np.argmin(identical))\n\nprint(f\"input shape          : {X.shape}\")\nprint(f\"rows identical to    : step {first_difference - 1}\")\nprint(f\"first differing step : {first_difference}\")\nprint(f\"identical before it  : {bool(identical[:first_difference].all())}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ninput shape          : (2, 157, 16)\nrows identical to    : step 78\nfirst differing step : 79\nidentical before it  : True\n```\n:::\n:::\n\n\nThe emulator cannot represent a larviciding programme running for years, or a routine\ndistribution channel that predates the campaign, since the pre-campaign period is described\nentirely by `eir`, `dn0_use`, `itn_use`, `irs_use`, `Q0`, `phi_bednets` and `seasonal`, and an\nexisting larviciding programme is already inside the estimated EIR.\n\n::: {.callout-important}\n## Future coverage\n\nLeaving `itn_future` and `dn0_future` at zero does not mean *keep the nets as they are*. It\nmeans *the nets are withdrawn from day 3285 onwards*. `irs_future` does not inherit `irs_use`\neither. To model an existing programme continuing, restate it, setting\n`itn_future` to the coverage the campaign sustains and `dn0_future` to the lethality of the\nnet. The same trap sits at [`run_scenarios`](../06-scenarios/run-scenarios.qmd), where\n`net_type_future`, `itn_future` and `irs_future` all default to nothing, so a `Scenario` that\nomits them withdraws the intervention. Nothing is raised. What comes back is a plausible\ntrajectory of the wrong scenario.\n:::\n\n## The time grid\n\nNothing about the time axis is passed in, and the emulator reconstructs it from four numbers in\nthe checkpoint's preprocessing config. Read those out rather than hard-coding them.\n\n::: {#c798af54 .cell execution_count=5}\n``` {.python .cell-code}\ncfg = artifact.preprocessing_config\n\nn_steps          = cfg[\"n_steps\"]\nwindow_size      = cfg[\"window_size\"]\nmodel_start_day  = cfg[\"model_start_day\"]\nintervention_day = cfg[\"intervention_day\"]\n\nprint(f\"n_steps          = {n_steps}\")\nprint(f\"window_size      = {window_size} days\")\nprint(f\"model_start_day  = {model_start_day}\")\nprint(f\"intervention_day = {intervention_day}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nn_steps          = 157\nwindow_size      = 14 days\nmodel_start_day  = 2190\nintervention_day = 3285\n```\n:::\n:::\n\n\nThe simulation behind the training data runs for longer than this. Its first six years are\nburn-in and discarded.\n\n::: {#295665fe .cell execution_count=6}\n``` {.python .cell-code}\nabs_t = model_start_day + window_size * np.arange(n_steps)\nyears = (abs_t - intervention_day) / 365\nidx_y9 = int(np.argmin(np.abs(abs_t - intervention_day)))\n\nprint(f\"abs_t  : day {abs_t[0]} to day {abs_t[-1]}\")\nprint(f\"years  : {years[0]:+.2f} to {years[-1]:+.2f}\")\nprint(f\"idx_y9 : {idx_y9}  (day {abs_t[idx_y9]})\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nabs_t  : day 2190 to day 4374\nyears  : -3.00 to +2.98\nidx_y9 : 78  (day 3282)\n```\n:::\n:::\n\n\n`abs_t` is the absolute simulation day of each window and `years` recentres it on the campaign,\nwhich is the axis worth plotting against. `idx_y9` is the index of the window nearest the\ncampaign, the ninth year of the simulation, where estiMINT's `prev_y9` is measured. At day 3282\nit is the last window before the switch.\n\nRead the baseline off `idx_y9` and check the emulator there against the prevalence fed to the\npipeline, rather than off the mean of the pre-campaign years, which open on the previous mass\ndistribution and close on the next and whose annual means are nowhere near `prev_y9`. They are\nnot a flat equilibrium. The shape they do have is plotted in\n[Plotting trajectories](plotting.qmd).\n\n::: {.callout-warning}\n## The training window\n\nThe simulation behind the training data runs for 12 years. The first 6 are burn-in, discarded so\nimmunity settles before the campaign. The emulator reproduces the last 6, the 157 fortnightly\nwindows returned here, with the campaign at day 3285 from the start of the simulation. The 12-year\nrun, the 6-year burn-in, the 157 windows, and the campaign day are fixed by the current training\nset. A later model may use a different window.\n:::\n\n## See also\n\nThese twelve covariates become a trajectory in [Calling the emulator](the-emulator.qmd).\n\n",
    "supporting": [
      "covariates_files"
    ],
    "filters": [],
    "includes": {}
  }
}