{
  "hash": "8a2d625ed5406c931c217267d56a62b4",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Pipeline architecture\"\n---\n\n\n\n\n`run_scenarios` sequences the net calculation, estiMINT's EIR estimation, and the stateMINT\nemulator, then assembles the result. It has no model of its own. The order matters, because\neach step consumes what the previous one produced.\n\n## The order of operations\n\nFor a list of scenarios, `run_scenarios` performs the same five steps in the same order\nevery time.\n\n1. **Bednet effects.** Each scenario carries a current net mix (`py_only`, `py_pbo`,\n   `py_pyrrole`, `py_ppf`) and a campaign (`net_type_future` at `itn_future` coverage).\n   Both go through [`calculate_dn0`](../04-estimint/nets-and-dn0.qmd) at the scenario's\n   resistance level, giving `dn0_use` and `itn_use` for today's nets and `dn0_future` and\n   `itn_future` for the campaign. If `itn_future` is zero, or `net_type_future` is unset,\n   the future effect is `DN0Result(0.0, 0.0)`, an explicit pair of zeros rather than a\n   copy of the present.\n2. **Effective LSM.** Pyriproxyfen suppresses emergence, so a PPF net does part of the\n   job of larval source management. The PPF share of the *current* mix is folded into the\n   LSM coverage the emulator sees:\n\n   $$\\texttt{lsm\\_eff} = \\min(\\texttt{py\\_ppf} \\times 0.248 + \\texttt{lsm},\\; 1.0)$$\n\n3. **EIR.** Each scenario is dispatched down one of three paths (below).\n4. **Covariate assembly.** The twelve static covariates are built for each scenario, with\n   the estimated EIR in the `eir` slot.\n5. **Emulation.** One batched `predict` call per predictor (prevalence and cases) across\n   every scenario at once.\n\n## The three EIR paths\n\n`EirTarget.input_mode` and `mosquito_delta` together decide how the baseline EIR is\nobtained. The scenarios are grouped, and each group is handled in one batched call.\n\n| Condition | Path |\n|---|---|\n| `input_mode == \"eir\"` | The supplied value is used unchanged. No model runs. |\n| `input_mode` is `\"prevalence\"` or `\"hbr\"`, with `mosquito_delta == 0` | The value is appended to the six intervention covariates as `prev_y9` or `hbr_y9`, and the matching XGBoost model predicts the EIR. |\n| `input_mode == \"prevalence\"` with a non-zero `mosquito_delta` | Routed to `estimate_eir_with_mosquito_delta`, which estimates the baseline EIR, converts it to an HBR, scales that HBR by `1 + mosquito_delta`, and reads the EIR back off the HBR model as a **ratio** against the round trip. |\n\nThe ratio in the third path exists because the prevalence → EIR → HBR → EIR round trip does\nnot close exactly. Taking the ratio of two HBR-model predictions cancels most of the\nround-trip error. So `mosquito_delta` is meaningful only for a prevalence input, and the\nother two modes ignore it silently, since neither performs the round trip that the ratio\ncorrects for.\n\nThe middle path is the only one that populates `eir_baseline` from a model, and the third\nthe only one that populates `hbr_baseline` and `hbr_new`. Those two columns are `NaN`\notherwise.\n\n## One batched call\n\nStep 5 is a single `predict` per predictor for the whole list, and the covariate dicts are\nstacked into one `(B, 157, 16)` tensor and pushed through the network once. A JAX forward\npass over ten scenarios costs barely more than one. A loop over `run_scenarios([s])` pays\nthe fixed overhead ten times, and re-traces the model for the new batch shape.\n\n::: {#9ea8c20b .cell execution_count=1}\n``` {.python .cell-code}\nimport time\nimport numpy as np\nimport pandas as pd\nfrom estimint import Scenario, EirTarget, run_scenarios, preload_models\n\npreload_models()\n\nsetting = dict(res_use=0.30, Q0=0.85, phi=0.80, seasonal=0.0, irs=0.0)\n\ngrid = [\n    Scenario(\n        name=f\"pbo_{cov:.2f}\", **setting, py_only=0.70,\n        eir_target=EirTarget(0.45, \"prevalence\"),\n        net_type_future=\"py_pbo\", itn_future=float(cov),\n    )\n    for cov in np.linspace(0.1, 0.9, 10)\n]\n\nrun_scenarios(grid)          # warm the batched shape\nrun_scenarios(grid[:1])      # warm the single-scenario shape\n\nt0 = time.perf_counter()\nbatched = run_scenarios(grid)\nt_batched = time.perf_counter() - t0\n\nt0 = time.perf_counter()\nlooped = pd.concat([run_scenarios([s]) for s in grid], ignore_index=True)\nt_looped = time.perf_counter() - t0\n\nprint(f\"one call, ten scenarios : {t_batched:.2f} s\")\nprint(f\"ten calls, one each     : {t_looped:.2f} s  ({t_looped / t_batched:.1f}x)\")\nprint(\"identical trajectories  :\",\n      np.allclose(np.stack(batched[\"prevalence\"]), np.stack(looped[\"prevalence\"])))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\none call, ten scenarios : 0.31 s\nten calls, one each     : 1.16 s  (3.7x)\nidentical trajectories  : True\n```\n:::\n:::\n\n\nPass a list. The results are identical either way, and the loop repeats the fixed overhead\nonce per scenario.\n\n## Effective LSM in the output\n\nThe fold in step 2 means the `lsm` column that comes back is not always the `lsm` that\nwent in. Half the population on PPF nets contributes `0.5 × 0.248 = 0.124` of effective\nlarval source management on top of whatever was supplied.\n\n::: {#f5978f1d .cell execution_count=2}\n``` {.python .cell-code}\nscenarios = [\n    Scenario(\n        name=\"pyrethroid now\", **setting, py_only=0.70, lsm=0.30,\n        eir_target=EirTarget(0.45, \"prevalence\"),\n        net_type_future=\"py_pbo\", itn_future=0.70,\n    ),\n    Scenario(\n        name=\"ppf now\", **setting, py_ppf=0.50, lsm=0.30,\n        eir_target=EirTarget(0.45, \"prevalence\"),\n        net_type_future=\"py_pbo\", itn_future=0.70,\n    ),\n]\n\nrun_scenarios(scenarios)[[\"name\", \"dn0_use\", \"itn_use\", \"lsm\", \"eir_baseline\"]]\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>name</th>\n      <th>dn0_use</th>\n      <th>itn_use</th>\n      <th>lsm</th>\n      <th>eir_baseline</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>pyrethroid now</td>\n      <td>0.311000</td>\n      <td>0.7</td>\n      <td>0.300</td>\n      <td>31.960129</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>ppf now</td>\n      <td>0.394717</td>\n      <td>0.5</td>\n      <td>0.424</td>\n      <td>29.129636</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThe fold reads the *current* mix only. A campaign that switches to PPF nets\n(`net_type_future=\"py_ppf\"`) raises `dn0_future` but adds nothing to `lsm`.\n\n## Pre-campaign masking\n\nThe emulator sees all twelve covariates at all 157 timesteps. Five of them (`dn0_future`,\n`itn_future`, `irs_future`, `lsm` and `routine`) are set to zero for every timestep before\nday 3285, and take their supplied value from that day on. The masking is applied in the\nfeature builder, in raw units, before standardisation.\n\n::: {#3be776da .cell execution_count=3}\n``` {.python .cell-code}\nfrom stateMINT.model import Mamba2Regressor\n\nart = Mamba2Regressor.from_pretrained(\n    \"dide-ic/stateMINT\", predictor=\"prevalence\", revision=\"v1.2.2\",\n)\nconfig = art.preprocessing_config\n\nkeep = dict(\n    eir=31.96, dn0_use=0.311, dn0_future=0.457, Q0=0.85, phi_bednets=0.80,\n    seasonal=0.0, routine=0.0, itn_use=0.70, irs_use=0.0,\n    itn_future=0.70, irs_future=0.0, lsm=0.0,\n)\nwithdraw = {**keep, \"dn0_future\": 0.0, \"itn_future\": 0.0}\n\nX = art.prepare_inputs([keep, withdraw])\n\nabs_t = np.arange(\n    config[\"model_start_day\"],\n    config[\"model_start_day\"] + config[\"window_size\"] * config[\"n_steps\"],\n    config[\"window_size\"],\n)\nbefore = abs_t < config[\"intervention_day\"]\n\nprint(\"after_intervention :\", config[\"after_intervention\"])\nprint(\"identical before day 3285 :\", np.allclose(X[0, before], X[1, before]))\nprint(\"identical after day 3285  :\", np.allclose(X[0, ~before], X[1, ~before]))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nafter_intervention : ['dn0_future', 'itn_future', 'irs_future', 'lsm', 'routine']\nidentical before day 3285 : True\nidentical after day 3285  : False\n```\n:::\n:::\n\n\nTwo scenarios that differ only in their campaign are the *same tensor* for the first three\nyears. The five after-intervention columns are the model's entire description of the\npost-campaign world. Nothing else in the vector carries a campaign.\n\nA zero in `itn_future` is a real zero. It is read as no net coverage from day 3285 onwards,\nand the model does not fill it in from `itn_use`. The `withdraw` scenario above is a\nwithdrawal because its `dn0_future` and `itn_future` are zero, and for no other reason.\n\n::: {.callout-important}\nThe `_future` fields do not carry the present forward, so leaving `itn_future` at 0, or\n`net_type_future` at `None`, models the nets being **withdrawn** at the campaign.\n`irs_future` does not inherit from `irs` either. To hold an intervention steady across the\ncampaign, you must restate it.\n:::\n\n## Next\n\n- [Mosquito density and EIR](../04-estimint/mosquito-density.qmd) — the ratio method in full.\n- [Covariates and the time grid](../05-statemint/covariates.qmd) — the twelve covariates and the 157 windows.\n- [estiMINT internals](estimint-internals.qmd) — what the XGBoost models do with those six covariates.\n\n",
    "supporting": [
      "architecture_files/figure-html"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}