{
  "hash": "976026da11c12d706ceb9ca5af3e2899",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"EIR, HBR, prevalence, and cases\"\n---\n\n\n\n\nTransmission intensity enters MINTverse as an EIR or an HBR and leaves it as under-five\nprevalence and clinical cases. Each of those four quantities is either a single number\ndescribing the setting in the year the campaign lands or a path through time, and that\ndistinction decides which package produces it.\n\n## The four quantities\n\nThe **entomological inoculation rate (EIR)** is infectious bites per person per year, and it\nsets the force of infection in the transmission model the emulator stands in for. It is the\nquantity `stateMINT` runs from. `estimint` infers it from a prevalence or from an HBR.\n\nThe **human biting rate (HBR)** is bites per person per year, infectious or not. It is the EIR\ndivided by the sporozoite rate, so the numbers are large, typically in the tens or hundreds of\nthousands per year. `mosquito_delta` scales the mosquito density, and it reaches the\ntransmission model through the HBR.\n\nPrevalence is reported throughout MINTverse as the under-five value on a 0 to 1 scale. It\nappears both as an input (`prev_y9`, a single number describing the setting at the decision\npoint) and as an output (a 157-step trajectory from the emulator).\n\nCases are clinical malaria episodes, all-age, per 1000 population, and an emulator output only,\nso nothing in the pipeline takes cases as an input and there is no cases-to-anything inversion\nto run. They are floored at zero.\n\n## Values and series\n\n| Quantity | What it is | Units | Value or series | Produced by |\n|---|---|---|---|---|\n| EIR | transmission intensity | infectious bites / person / year | single value | `estimint` |\n| HBR | biting pressure | bites / person / year | single value | `estimint` |\n| Prevalence | infected share, under-5 | proportion, 0–1 | input value **or** 157-step series | input or `stateMINT` |\n| Cases | clinical episodes, all-age | per 1000 population | 157-step series | `stateMINT` |\n\n`estimint` returns an equilibrium, the transmission intensity that a setting sustains at the\nmoment the decision is taken. It has no time axis and cannot acquire one, so it cannot say what\nthe EIR will be two years after a PBO campaign, only what it would be in a setting that had\nalready settled under one.\n\nOnly `stateMINT` returns a path. A trajectory, a comparison of trajectories, or an endline\nvalue three years out has to come from the emulator.\n\n::: {.callout-note}\n## EIR and equilibrium\n\n`estimate_eir_with_mosquito_delta` returns two numbers, `eir_baseline` and `eir_new`. Both are\nequilibria. `eir_new` is the intensity a setting would settle at with a different mosquito\ndensity, not the EIR at some later date, so the two values do not bracket a trajectory between\nthem. Any transient between them is the emulator's business.\n:::\n\n## The time grid\n\nEvery trajectory the emulator returns is laid on one grid of 157 fortnightly steps, built\naround the day the campaign lands. The simulations behind `stateMINT` run a six-year burn-in\nfirst, letting the transmission model settle into equilibrium from arbitrary initial\nconditions. That burn-in is **discarded** and never reaches the emulator.\n\nWhat remains starts at day 2190, the start of year 6, and runs in 14-day windows. The first\nthree years are pre-campaign baseline, during which nothing changes. At day 3285, the start of\nyear 9, the campaign switches on. `dn0_future`, `itn_future`, `irs_future`, `lsm` and `routine`\nare zero for every step before that day, and take their value from it onwards. Roughly three\nyears of response follow.\n\nThe grid is written into the artefact rather than hard-coded, so it can be read back.\n\n::: {#957f10ea .cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nfrom stateMINT.model import Mamba2Regressor\n\nartifact = Mamba2Regressor.from_pretrained(\n    \"dide-ic/stateMINT\", predictor=\"prevalence\", revision=\"v1.2.2\",\n)\ncfg = artifact.preprocessing_config\n\nabs_t = cfg[\"model_start_day\"] + cfg[\"window_size\"] * np.arange(cfg[\"n_steps\"])\nyears = (abs_t - cfg[\"intervention_day\"]) / 365\nidx_y9 = int(np.argmin(np.abs(abs_t - cfg[\"intervention_day\"])))\n\nprint(f\"steps                {cfg['n_steps']}\")\nprint(f\"window               {cfg['window_size']} days\")\nprint(f\"grid starts          day {abs_t[0]}\")\nprint(f\"campaign             day {cfg['intervention_day']} -> step {idx_y9} (day {abs_t[idx_y9]})\")\nprint(f\"grid ends            day {abs_t[-1]}\")\nprint(f\"years from campaign  {years[0]:+.2f} to {years[-1]:+.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nsteps                157\nwindow               14 days\ngrid starts          day 2190\ncampaign             day 3285 -> step 78 (day 3282)\ngrid ends            day 4374\nyears from campaign  -3.00 to +2.98\n```\n:::\n:::\n\n\nThe name `prev_y9` is literal. It is the annual mean under-five prevalence in year 9, the year\nthe campaign lands. Passing a measured prevalence to `estimint` asserts that this is the\nsetting as it stands on the day the nets are distributed.\n\nThe three pre-campaign years serve as a sanity check. No campaign acts on them, so they show\nthe setting under the nets it already has, and a baseline that starts somewhere other than the\nprevalence you supplied means the covariates do not describe the setting you think they do.\nPlotting in `years` rather than raw days puts the campaign at zero, so scenarios line up on one\nx-axis.\n\n## See also\n\nThe net mix, the spraying coverage and the larval control that switch on at day 3285 are\ndescribed in [Interventions and nets](interventions.qmd), and the three estimators and the\nemulator that consume them in [The models](models.qmd). Please see [Estimating EIR from\nprevalence](../04-estimint/estimating-eir.qmd) for the inversion in practice.\n\n",
    "supporting": [
      "equilibrium_files"
    ],
    "filters": [],
    "includes": {}
  }
}